export interface AsciiItem {
  char: string;
  name: string;
  keywords: string[];
}

export interface AsciiCategory {
  slug: string;
  name: string;
  description: string;
  icon: string;
  items: AsciiItem[];
}

export const ASCII_CATEGORIES: AsciiCategory[] = [
  {
    slug: 'hearts',
    name: 'Hearts & Love',
    description: 'Copy and paste heart symbols, love characters, and romantic ASCII art for social media, messages, and creative projects.',
    icon: '♥',
    items: [
      { char: '♥', name: 'Black Heart Suit', keywords: ['heart', 'love', 'red'] },
      { char: '♡', name: 'White Heart Suit', keywords: ['heart', 'outline', 'love'] },
      { char: '❤', name: 'Heavy Black Heart', keywords: ['heart', 'love', 'emoji'] },
      { char: '❤️', name: 'Red Heart Emoji', keywords: ['heart', 'love', 'red'] },
      { char: '🧡', name: 'Orange Heart', keywords: ['heart', 'orange'] },
      { char: '💛', name: 'Yellow Heart', keywords: ['heart', 'yellow'] },
      { char: '💚', name: 'Green Heart', keywords: ['heart', 'green'] },
      { char: '💙', name: 'Blue Heart', keywords: ['heart', 'blue'] },
      { char: '💜', name: 'Purple Heart', keywords: ['heart', 'purple'] },
      { char: '🖤', name: 'Black Heart', keywords: ['heart', 'black'] },
      { char: '🤍', name: 'White Heart', keywords: ['heart', 'white'] },
      { char: '🤎', name: 'Brown Heart', keywords: ['heart', 'brown'] },
      { char: '💕', name: 'Two Hearts', keywords: ['hearts', 'love', 'couple'] },
      { char: '💞', name: 'Revolving Hearts', keywords: ['hearts', 'spinning'] },
      { char: '💓', name: 'Beating Heart', keywords: ['heart', 'pulse'] },
      { char: '💗', name: 'Growing Heart', keywords: ['heart', 'growing'] },
      { char: '💖', name: 'Sparkling Heart', keywords: ['heart', 'sparkle'] },
      { char: '💝', name: 'Heart with Ribbon', keywords: ['heart', 'gift', 'ribbon'] },
      { char: '💘', name: 'Heart with Arrow', keywords: ['heart', 'cupid', 'arrow'] },
      { char: '💟', name: 'Heart Decoration', keywords: ['heart', 'decoration'] },
      { char: '❣', name: 'Heavy Heart Exclamation', keywords: ['heart', 'exclamation'] },
      { char: '❥', name: 'Rotated Heavy Black Heart Bullet', keywords: ['heart', 'rotated'] },
      { char: '🫀', name: 'Anatomical Heart', keywords: ['heart', 'anatomical', 'organ'] },
      { char: '♥‿♥', name: 'Happy Face with Hearts', keywords: ['heart', 'face', 'happy', 'kawaii'] },
      { char: '(♥ω♥*)', name: 'Blushing Hearts Face', keywords: ['heart', 'blush', 'kawaii'] },
      { char: '(っ˘ω˘ς )', name: 'Cozy Huggy', keywords: ['cute', 'hug', 'kawaii'] },
      { char: '(づ｡◕‿‿◕｡)づ', name: 'Reaching Out Hug', keywords: ['hug', 'cute', 'kawaii'] },
    ],
  },
  {
    slug: 'stars',
    name: 'Stars & Sparkles',
    description: 'Copy and paste star symbols, sparkle characters, and celestial ASCII art for decorating text, social media bios, and messages.',
    icon: '★',
    items: [
      { char: '★', name: 'Black Star', keywords: ['star', 'filled', 'black'] },
      { char: '☆', name: 'White Star', keywords: ['star', 'outline', 'white'] },
      { char: '✦', name: 'Black Four Pointed Star', keywords: ['star', 'four', 'pointed'] },
      { char: '✧', name: 'White Four Pointed Star', keywords: ['star', 'four', 'outline'] },
      { char: '✩', name: 'Stress Outlined White Star', keywords: ['star', 'fancy'] },
      { char: '✪', name: 'Circled White Star', keywords: ['star', 'circle'] },
      { char: '✫', name: 'Open Centre Black Star', keywords: ['star', 'open'] },
      { char: '✬', name: 'Black Centre White Star', keywords: ['star', 'center'] },
      { char: '✭', name: 'Outlined Black Star', keywords: ['star', 'outlined'] },
      { char: '✮', name: 'Heavy Outlined Black Star', keywords: ['star', 'heavy'] },
      { char: '✯', name: 'Pinwheel Star', keywords: ['star', 'pinwheel'] },
      { char: '✰', name: 'Shadowed White Star', keywords: ['star', 'shadow'] },
      { char: '⭐', name: 'Star Emoji', keywords: ['star', 'yellow', 'emoji'] },
      { char: '🌟', name: 'Glowing Star', keywords: ['star', 'glow', 'emoji'] },
      { char: '💫', name: 'Dizzy Star', keywords: ['star', 'dizzy', 'spinning'] },
      { char: '⚡', name: 'Lightning Star', keywords: ['star', 'lightning', 'zap'] },
      { char: '✨', name: 'Sparkles', keywords: ['sparkle', 'shine', 'magic'] },
      { char: '🌠', name: 'Shooting Star', keywords: ['star', 'shooting', 'wish'] },
      { char: '☀', name: 'Sun', keywords: ['sun', 'day', 'bright'] },
      { char: '☽', name: 'Crescent Moon', keywords: ['moon', 'crescent', 'night'] },
      { char: '☾', name: 'Last Quarter Moon', keywords: ['moon', 'night'] },
      { char: '⋆｡°✩', name: 'Star Cluster Deco', keywords: ['star', 'decoration', 'cute'] },
      { char: '°•⋆⁺₊⋆', name: 'Star Trail', keywords: ['star', 'trail', 'deco'] },
      { char: '✦ ✧ ✦', name: 'Star Row', keywords: ['stars', 'row', 'divider'] },
    ],
  },
  {
    slug: 'arrows',
    name: 'Arrows & Directions',
    description: 'Copy and paste arrow symbols and directional characters for presentations, diagrams, documents, and social media.',
    icon: '→',
    items: [
      { char: '→', name: 'Rightwards Arrow', keywords: ['arrow', 'right', 'next'] },
      { char: '←', name: 'Leftwards Arrow', keywords: ['arrow', 'left', 'back'] },
      { char: '↑', name: 'Upwards Arrow', keywords: ['arrow', 'up', 'increase'] },
      { char: '↓', name: 'Downwards Arrow', keywords: ['arrow', 'down', 'decrease'] },
      { char: '↗', name: 'North East Arrow', keywords: ['arrow', 'diagonal', 'up-right'] },
      { char: '↘', name: 'South East Arrow', keywords: ['arrow', 'diagonal', 'down-right'] },
      { char: '↙', name: 'South West Arrow', keywords: ['arrow', 'diagonal', 'down-left'] },
      { char: '↖', name: 'North West Arrow', keywords: ['arrow', 'diagonal', 'up-left'] },
      { char: '↔', name: 'Left Right Arrow', keywords: ['arrow', 'both', 'horizontal'] },
      { char: '↕', name: 'Up Down Arrow', keywords: ['arrow', 'both', 'vertical'] },
      { char: '⇒', name: 'Rightwards Double Arrow', keywords: ['arrow', 'double', 'implies'] },
      { char: '⇐', name: 'Leftwards Double Arrow', keywords: ['arrow', 'double', 'left'] },
      { char: '⇑', name: 'Upwards Double Arrow', keywords: ['arrow', 'double', 'up'] },
      { char: '⇓', name: 'Downwards Double Arrow', keywords: ['arrow', 'double', 'down'] },
      { char: '⇔', name: 'Left Right Double Arrow', keywords: ['arrow', 'double', 'both'] },
      { char: '➜', name: 'Heavy Round-Tipped Rightwards Arrow', keywords: ['arrow', 'bold', 'right'] },
      { char: '➤', name: 'Black Rightwards Arrowhead', keywords: ['arrow', 'filled', 'right'] },
      { char: '➡', name: 'Black Rightwards Arrow', keywords: ['arrow', 'black', 'right'] },
      { char: '▶', name: 'Play / Right Triangle', keywords: ['play', 'arrow', 'right', 'triangle'] },
      { char: '◀', name: 'Left Triangle', keywords: ['arrow', 'left', 'triangle'] },
      { char: '▲', name: 'Up Triangle', keywords: ['arrow', 'up', 'triangle'] },
      { char: '▼', name: 'Down Triangle', keywords: ['arrow', 'down', 'triangle'] },
      { char: '↺', name: 'Anticlockwise Open Circle Arrow', keywords: ['arrow', 'refresh', 'undo'] },
      { char: '↻', name: 'Clockwise Open Circle Arrow', keywords: ['arrow', 'refresh', 'redo'] },
      { char: '⟶', name: 'Long Rightwards Arrow', keywords: ['arrow', 'long', 'right'] },
      { char: '⟵', name: 'Long Leftwards Arrow', keywords: ['arrow', 'long', 'left'] },
    ],
  },
  {
    slug: 'text-faces',
    name: 'Text Faces & Kaomoji',
    description: 'Copy and paste ASCII text faces, emoticons, and Japanese kaomoji for chat, social media, and fun expressions.',
    icon: '(ツ)',
    items: [
      { char: '¯\\_(ツ)_/¯', name: 'Shrug', keywords: ['shrug', 'meh', 'whatever'] },
      { char: '( ͡° ͜ʖ ͡°)', name: 'Lenny Face', keywords: ['lenny', 'face', 'suggestive'] },
      { char: '(╯°□°）╯︵ ┻━┻', name: 'Table Flip', keywords: ['flip', 'table', 'angry'] },
      { char: '┬─┬ノ( º _ ºノ)', name: 'Table Restore', keywords: ['table', 'calm', 'restore'] },
      { char: '(ノ°益°)ノ彡┻━┻', name: 'Rage Table Flip', keywords: ['rage', 'flip', 'angry'] },
      { char: '(づ￣ ³￣)づ', name: 'Kissing Face', keywords: ['kiss', 'smooch', 'love'] },
      { char: '(ʘ‿ʘ)', name: 'Wide Eyes Smile', keywords: ['smile', 'happy', 'wide eyes'] },
      { char: '(◕‿◕)', name: 'Happy Cute Face', keywords: ['happy', 'cute', 'smile'] },
      { char: '(；一_一)', name: 'Unamused Face', keywords: ['unamused', 'boring', 'flat'] },
      { char: '(≧▽≦)', name: 'Excited Grin', keywords: ['excited', 'happy', 'grin'] },
      { char: '(；☉_☉)', name: 'Shocked Face', keywords: ['shocked', 'surprised', 'wide eyes'] },
      { char: '(T_T)', name: 'Crying Face', keywords: ['cry', 'sad', 'tears'] },
      { char: '(^_^)', name: 'Simple Smile', keywords: ['smile', 'happy', 'simple'] },
      { char: '(>.<)', name: 'Struggling Face', keywords: ['struggle', 'tense', 'frustrated'] },
      { char: '(ง •̀_•́)ง', name: 'Fighting Stance', keywords: ['fight', 'determined', 'fists'] },
      { char: '٩(◕‿◕｡)۶', name: 'Raised Arms Happy', keywords: ['happy', 'excited', 'arms up'] },
      { char: '(｡◕‿◕｡)', name: 'Puppy Eyes', keywords: ['cute', 'puppy', 'big eyes'] },
      { char: '凸(¬‿¬)', name: 'Middle Finger Smug', keywords: ['smug', 'rude'] },
      { char: '(◡‿◡✿)', name: 'Flower Girl Smile', keywords: ['smile', 'flower', 'cute'] },
      { char: '(ᵔᴥᵔ)', name: 'Bear Face', keywords: ['bear', 'cute', 'animal'] },
      { char: '≧^◡^≦', name: 'Cat Grin', keywords: ['cat', 'smile', 'grin'] },
      { char: 'ʕ•ᴥ•ʔ', name: 'Bear Hug', keywords: ['bear', 'hug', 'cute'] },
      { char: '(=^•ω•^=)', name: 'Cat Face', keywords: ['cat', 'cute', 'kawaii'] },
      { char: 'ヽ(´▽`)/', name: 'Cheering Arms Up', keywords: ['cheer', 'happy', 'yay'] },
    ],
  },
  {
    slug: 'symbols',
    name: 'Symbols & Special Chars',
    description: 'Copy and paste special symbols, currency signs, mathematical symbols, and typographic characters for documents and design.',
    icon: '©',
    items: [
      { char: '©', name: 'Copyright', keywords: ['copyright', 'legal', 'rights'] },
      { char: '®', name: 'Registered Trademark', keywords: ['registered', 'trademark', 'legal'] },
      { char: '™', name: 'Trademark', keywords: ['trademark', 'brand', 'tm'] },
      { char: '℠', name: 'Service Mark', keywords: ['service', 'mark', 'sm'] },
      { char: '°', name: 'Degree', keywords: ['degree', 'temperature', 'angle'] },
      { char: '∞', name: 'Infinity', keywords: ['infinity', 'forever', 'loop'] },
      { char: '±', name: 'Plus-Minus', keywords: ['plus', 'minus', 'math'] },
      { char: '≈', name: 'Almost Equal', keywords: ['approximately', 'equal', 'math'] },
      { char: '≠', name: 'Not Equal', keywords: ['not equal', 'different', 'math'] },
      { char: '≤', name: 'Less Than or Equal', keywords: ['less', 'equal', 'math'] },
      { char: '≥', name: 'Greater Than or Equal', keywords: ['greater', 'equal', 'math'] },
      { char: '×', name: 'Multiplication Sign', keywords: ['multiply', 'times', 'cross'] },
      { char: '÷', name: 'Division Sign', keywords: ['divide', 'division', 'math'] },
      { char: '√', name: 'Square Root', keywords: ['root', 'sqrt', 'math'] },
      { char: 'π', name: 'Pi', keywords: ['pi', 'circle', 'math'] },
      { char: 'Σ', name: 'Sigma / Sum', keywords: ['sigma', 'sum', 'math'] },
      { char: 'μ', name: 'Micro / Mu', keywords: ['micro', 'mu', 'greek'] },
      { char: 'Δ', name: 'Delta / Change', keywords: ['delta', 'change', 'triangle'] },
      { char: '$', name: 'Dollar', keywords: ['dollar', 'usd', 'currency'] },
      { char: '€', name: 'Euro', keywords: ['euro', 'eur', 'currency'] },
      { char: '£', name: 'Pound', keywords: ['pound', 'gbp', 'currency'] },
      { char: '¥', name: 'Yen', keywords: ['yen', 'jpy', 'currency'] },
      { char: '₩', name: 'Won', keywords: ['won', 'krw', 'korea', 'currency'] },
      { char: '₿', name: 'Bitcoin', keywords: ['bitcoin', 'btc', 'crypto'] },
      { char: '§', name: 'Section Sign', keywords: ['section', 'legal', 'paragraph'] },
      { char: '¶', name: 'Pilcrow / Paragraph', keywords: ['paragraph', 'pilcrow', 'text'] },
      { char: '†', name: 'Dagger', keywords: ['dagger', 'cross', 'footnote'] },
      { char: '‡', name: 'Double Dagger', keywords: ['double', 'dagger', 'footnote'] },
      { char: '•', name: 'Bullet', keywords: ['bullet', 'dot', 'list'] },
      { char: '…', name: 'Ellipsis', keywords: ['ellipsis', 'dots', 'continue'] },
    ],
  },
  {
    slug: 'borders',
    name: 'Borders & Dividers',
    description: 'Copy and paste ASCII border lines, decorative dividers, and separators for text formatting, social media bios, and notes.',
    icon: '═',
    items: [
      { char: '─────────────────', name: 'Thin Line', keywords: ['line', 'divider', 'separator'] },
      { char: '═════════════════', name: 'Double Line', keywords: ['double', 'line', 'divider'] },
      { char: '━━━━━━━━━━━━━━━━━', name: 'Bold Line', keywords: ['bold', 'line', 'thick'] },
      { char: '· · · · · · · · ·', name: 'Dotted Line', keywords: ['dots', 'dotted', 'divider'] },
      { char: '- - - - - - - - -', name: 'Dashed Line', keywords: ['dashed', 'line', 'divider'] },
      { char: '~ ~ ~ ~ ~ ~ ~ ~ ~', name: 'Wave Line', keywords: ['wave', 'tilde', 'divider'] },
      { char: '≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈≈', name: 'Double Wave', keywords: ['wave', 'double', 'divider'] },
      { char: '▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬', name: 'Block Bar', keywords: ['block', 'bar', 'divider'] },
      { char: '░░░░░░░░░░░░░░░░░', name: 'Light Block', keywords: ['light', 'block', 'shade'] },
      { char: '▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒', name: 'Medium Block', keywords: ['medium', 'block', 'shade'] },
      { char: '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓', name: 'Dark Block', keywords: ['dark', 'block', 'shade'] },
      { char: '████████████████', name: 'Full Block', keywords: ['full', 'block', 'solid'] },
      { char: '✦ ✦ ✦ ✦ ✦ ✦ ✦ ✦', name: 'Star Divider', keywords: ['star', 'divider', 'fancy'] },
      { char: '❖ ─ ─ ─ ─ ─ ─ ❖', name: 'Diamond Border', keywords: ['diamond', 'border', 'fancy'] },
      { char: '•·.·´¯`·.·•', name: 'Fancy Center Deco', keywords: ['fancy', 'decoration', 'center'] },
      { char: '【 】', name: 'Corner Brackets', keywords: ['bracket', 'corner', 'cjk'] },
      { char: '「 」', name: 'Japanese Brackets', keywords: ['bracket', 'japanese', 'quote'] },
      { char: '｢ ｣', name: 'Halfwidth Corner Brackets', keywords: ['bracket', 'halfwidth'] },
      { char: '⌐¬⌐¬', name: 'Angle Corner', keywords: ['angle', 'corner', 'tech'] },
      { char: '»»————————————————————«', name: 'Arrow Divider', keywords: ['arrow', 'divider', 'fancy'] },
    ],
  },
  {
    slug: 'checkmarks',
    name: 'Check Marks & Status',
    description: 'Copy and paste check marks, X marks, ballot boxes, and status symbols for lists, documents, and to-do items.',
    icon: '✓',
    items: [
      { char: '✓', name: 'Check Mark', keywords: ['check', 'tick', 'yes'] },
      { char: '✔', name: 'Heavy Check Mark', keywords: ['check', 'heavy', 'bold'] },
      { char: '☑', name: 'Ballot Box with Check', keywords: ['check', 'box', 'done'] },
      { char: '✅', name: 'White Heavy Check Mark Emoji', keywords: ['check', 'green', 'done', 'emoji'] },
      { char: '☒', name: 'Ballot Box with X', keywords: ['x', 'box', 'cross'] },
      { char: '✗', name: 'Ballot X', keywords: ['x', 'cross', 'no'] },
      { char: '✘', name: 'Heavy Ballot X', keywords: ['x', 'cross', 'no', 'heavy'] },
      { char: '❌', name: 'Cross Mark Emoji', keywords: ['x', 'cross', 'no', 'emoji'] },
      { char: '⭕', name: 'Heavy Large Circle', keywords: ['circle', 'yes', 'correct'] },
      { char: '❎', name: 'Negative Squared Cross Mark', keywords: ['x', 'cross', 'box'] },
      { char: '☐', name: 'Empty Ballot Box', keywords: ['box', 'empty', 'todo'] },
      { char: '□', name: 'White Square Box', keywords: ['box', 'empty', 'square'] },
      { char: '■', name: 'Black Square', keywords: ['box', 'filled', 'square'] },
      { char: '▪', name: 'Small Black Square', keywords: ['bullet', 'small', 'square'] },
      { char: '▸', name: 'Small Right Triangle', keywords: ['bullet', 'arrow', 'list'] },
      { char: '◆', name: 'Black Diamond', keywords: ['diamond', 'bullet', 'filled'] },
      { char: '◇', name: 'White Diamond', keywords: ['diamond', 'bullet', 'outline'] },
      { char: '⚪', name: 'White Circle', keywords: ['circle', 'empty', 'dot'] },
      { char: '⚫', name: 'Black Circle', keywords: ['circle', 'filled', 'dot'] },
      { char: '🔴', name: 'Red Circle', keywords: ['red', 'circle', 'status', 'stop'] },
      { char: '🟡', name: 'Yellow Circle', keywords: ['yellow', 'circle', 'status', 'warning'] },
      { char: '🟢', name: 'Green Circle', keywords: ['green', 'circle', 'status', 'ok'] },
    ],
  },
  {
    slug: 'flowers',
    name: 'Flowers & Nature',
    description: 'Copy and paste flower symbols, leaf characters, and nature ASCII art for decoration, social media, and creative writing.',
    icon: '✿',
    items: [
      { char: '✿', name: 'White Florette', keywords: ['flower', 'white', 'decor'] },
      { char: '❀', name: 'White Florette Bold', keywords: ['flower', 'bold', 'decor'] },
      { char: '✾', name: 'Six Petalled Black and White Florette', keywords: ['flower', 'six', 'petal'] },
      { char: '❁', name: 'Eight Petalled Outlined Black Florette', keywords: ['flower', 'eight', 'petal'] },
      { char: '❃', name: 'Heavy Teardrop-Spoked Pinwheel Asterisk', keywords: ['flower', 'pinwheel'] },
      { char: '❋', name: 'Heavy Eight Teardrop-Spoked Propeller Asterisk', keywords: ['flower', 'propeller'] },
      { char: '🌸', name: 'Cherry Blossom', keywords: ['sakura', 'cherry', 'spring'] },
      { char: '🌺', name: 'Hibiscus', keywords: ['hibiscus', 'tropical', 'flower'] },
      { char: '🌻', name: 'Sunflower', keywords: ['sunflower', 'summer', 'yellow'] },
      { char: '🌹', name: 'Rose', keywords: ['rose', 'red', 'romance'] },
      { char: '🌷', name: 'Tulip', keywords: ['tulip', 'spring', 'pink'] },
      { char: '🌼', name: 'Blossom', keywords: ['blossom', 'daisy', 'spring'] },
      { char: '💐', name: 'Bouquet', keywords: ['bouquet', 'flowers', 'gift'] },
      { char: '🍀', name: 'Four Leaf Clover', keywords: ['clover', 'lucky', 'green'] },
      { char: '🍃', name: 'Leaf Fluttering', keywords: ['leaf', 'wind', 'nature'] },
      { char: '🌿', name: 'Herb', keywords: ['herb', 'green', 'plant'] },
      { char: '☘', name: 'Shamrock', keywords: ['shamrock', 'irish', 'clover'] },
      { char: '🌱', name: 'Seedling', keywords: ['seedling', 'grow', 'plant'] },
      { char: '🌾', name: 'Sheaf of Rice', keywords: ['rice', 'grain', 'harvest'] },
      { char: '🍁', name: 'Maple Leaf', keywords: ['maple', 'autumn', 'canada'] },
    ],
  },
  {
    slug: 'box-drawing',
    name: 'Box Drawing',
    description: 'Copy and paste box drawing characters for ASCII tables, borders, diagrams, and terminal-style formatting.',
    icon: '┼',
    items: [
      { char: '┌─────┐', name: 'Top Border', keywords: ['box', 'top', 'corner', 'border'] },
      { char: '│     │', name: 'Side Border', keywords: ['box', 'side', 'vertical'] },
      { char: '└─────┘', name: 'Bottom Border', keywords: ['box', 'bottom', 'corner', 'border'] },
      { char: '╔═════╗', name: 'Double Box Top', keywords: ['double', 'box', 'top', 'corner'] },
      { char: '║     ║', name: 'Double Box Side', keywords: ['double', 'box', 'side'] },
      { char: '╚═════╝', name: 'Double Box Bottom', keywords: ['double', 'box', 'bottom'] },
      { char: '┼', name: 'Cross Junction', keywords: ['cross', 'junction', 'table'] },
      { char: '├', name: 'Left Junction', keywords: ['left', 'junction', 'tree'] },
      { char: '┤', name: 'Right Junction', keywords: ['right', 'junction'] },
      { char: '┬', name: 'Top Junction', keywords: ['top', 'junction'] },
      { char: '┴', name: 'Bottom Junction', keywords: ['bottom', 'junction'] },
      { char: '╬', name: 'Double Cross', keywords: ['double', 'cross', 'table'] },
      { char: '╠', name: 'Double Left Junction', keywords: ['double', 'left'] },
      { char: '╣', name: 'Double Right Junction', keywords: ['double', 'right'] },
      { char: '╦', name: 'Double Top Junction', keywords: ['double', 'top'] },
      { char: '╩', name: 'Double Bottom Junction', keywords: ['double', 'bottom'] },
      { char: '┌──┬──┐\n│  │  │\n├──┼──┤\n│  │  │\n└──┴──┘', name: '2×2 Table', keywords: ['table', 'grid', '2x2'] },
      { char: '╭────╮\n│    │\n╰────╯', name: 'Rounded Box', keywords: ['rounded', 'box', 'corner'] },
      { char: '▛▀▀▜\n▌  ▐\n▙▄▄▟', name: 'Block Box', keywords: ['block', 'box', 'solid'] },
    ],
  },
  {
    slug: 'animals',
    name: 'Animal Faces',
    description: 'Copy and paste ASCII animal faces, cute kawaii animals, and text art animals for chat, social media, and fun messages.',
    icon: '(=^.^=)',
    items: [
      { char: '(=^.^=)', name: 'Cat Face', keywords: ['cat', 'kitten', 'cute'] },
      { char: '(=^・ω・^=)', name: 'Fluffy Cat', keywords: ['cat', 'fluffy', 'kawaii'] },
      { char: 'ʕ•ᴥ•ʔ', name: 'Bear', keywords: ['bear', 'hug', 'cute'] },
      { char: '(•ᴥ•)', name: 'Dog Snout', keywords: ['dog', 'snout', 'animal'] },
      { char: 'V●ᴥ●V', name: 'Dog Face', keywords: ['dog', 'face', 'ears'] },
      { char: '(◕‿◕)', name: 'Puppy', keywords: ['puppy', 'cute', 'big eyes'] },
      { char: '>°))))彡', name: 'Fish', keywords: ['fish', 'swim', 'water'] },
      { char: '<°)))><', name: 'Simple Fish', keywords: ['fish', 'simple', 'swim'] },
      { char: '(>°oo°)>', name: 'Fish Face', keywords: ['fish', 'face', 'bubbles'] },
      { char: '🐰ω🐰', name: 'Bunny Face', keywords: ['bunny', 'rabbit', 'cute'] },
      { char: '(ˆ_ˆ)o自自o(ˆ_ˆ)', name: 'Cheers with Friends', keywords: ['cheer', 'toast', 'friends'] },
      { char: '( •_•)\n( •_•)>⌐■-■\n(⌐■_■)', name: 'Deal With It', keywords: ['deal', 'sunglasses', 'cool'] },
      { char: '/\\_/\\\n( o.o )\n > ^ <', name: 'Sitting Cat', keywords: ['cat', 'sitting', 'full body'] },
      { char: '   ^___^\n  (o . o)\n  (> Y <)', name: 'Owl', keywords: ['owl', 'bird', 'wise'] },
      { char: 'U ´ᴥ` U', name: 'Bear Paws', keywords: ['bear', 'paws', 'cute'] },
      { char: '(ᵔᴥᵔ)', name: 'Happy Bear', keywords: ['bear', 'happy', 'smile'] },
    ],
  },
];

export function getAsciiCategoryBySlug(slug: string): AsciiCategory | undefined {
  return ASCII_CATEGORIES.find(c => c.slug === slug);
}
